### ISSUE TITLE
В запрос get accident/list из главного экрана добавить координаты

### ISSUE THREAD

**Issue by elagin** [rjhdby/android_motoDTP_v2#32]
При открытии главного окна получать текущие координаты и отправлять запрос на сервер для загрузки ближайших инцидентов.

**Comment by Trunker2010** [comment]
2021-05-19 20:34:49.877 29630-31669/motocitizen.main I/okhttp.OkHttpClient: --> GET http://188.166.126.84:8080/v1/accident/list/?depth=999&lat=55.7300684&lon=37.4133884

**Comment by elagin** [comment]
Так же у нас нет остановки определения координат при сворачивании приложения и возобновлении, при разворачивании обратно: https://developer.android.com/training/location/request-updates#stop-updates
