### ISSUE TITLE
Изменить текст на маркере карты для свежего события.

### ISSUE THREAD

**Issue by elagin** [rjhdby/android_motoDTP_v2#62]
![Screenshot_20210519-123329_Motodtpinfo 1](https://user-images.githubusercontent.com/611744/118790512-8162a000-b89e-11eb-8004-6f839279f766.jpg)
Если событие создано только что, не писать слово "назад".

**Comment by Trunker2010** [comment]
![Screenshot_20210630_125650_motocitizen.main.jpg](https://user-images.githubusercontent.com/47688469/123942191-91909380-d9a3-11eb-90cc-700de38d5caf.jpg)
![Screenshot_20210630_130920_motocitizen.main.jpg](https://user-images.githubusercontent.com/47688469/123943080-73776300-d9a4-11eb-9451-d6f745f1e683.jpg)
