### ISSUE TITLE
Реализовать окно с настройками

### ISSUE THREAD

**Issue by elagin** [rjhdby/android_motoDTP_v2#68]
Реализовать отдельное Activity, переход в которое должен происходить из меню, как в старом приложении.
Пункты:
**Дистанция для поиска** - целочисленное поле с расстоянием в километрах (поле radius для запроса /accident/list). _Значение по умолчанию: 200_
**Глубина поиска** - целочисленное поле. Для обычных юзеров не больше 24 часов. (поле depth для запроса /accident/list) _Значение по умолчанию: 24_
**Учетная запись** - отображать имя пользователя и кнопку "выход".

**Comment by Trunker2010** [comment]
![Screenshot_20210528_192708_motocitizen.main.jpg](https://user-images.githubusercontent.com/47688469/120014495-cdbe8600-bfea-11eb-825d-b70496c3fcdc.jpg)
