### ISSUE TITLE
Реализовать отображение списка инцидентов на главном экране.

### ISSUE THREAD

**Issue by elagin** [rjhdby/android_motoDTP_v2#7]

**Comment by Trunker2010** [comment]
![Screenshot_20210422_130310](https://user-images.githubusercontent.com/47688469/115698741-a29ea200-a36d-11eb-9893-9c360432b31a.png)

**Comment by Trunker2010** [comment]
![Screenshot_1619288299](https://user-images.githubusercontent.com/47688469/115968914-bc451280-a542-11eb-8132-884d4e49d38a.png)

**Comment by Trunker2010** [comment]
![Screenshot_1619523109](https://user-images.githubusercontent.com/47688469/116235236-47eab900-a766-11eb-9035-2e06579ce4c7.png)

**Comment by Trunker2010** [comment]
![Screenshot_1619523109](https://user-images.githubusercontent.com/47688469/116235338-6355c400-a766-11eb-94ba-f9d76facdbba.png)
