### ISSUE TITLE
Двойное меню на экране информации об инциденте.

### ISSUE THREAD

**Issue by elagin** [rjhdby/android_motoDTP_v2#93]
![image](https://user-images.githubusercontent.com/611744/120502540-2f0b9e00-c3cb-11eb-97e2-a3244aae3f2f.png)

**Comment by Trunker2010** [comment]
![Screenshot_20210603_142038_motocitizen.main.jpg](https://user-images.githubusercontent.com/47688469/120636887-e4dff680-c476-11eb-942b-3921f2e2a823.jpg)
